spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sm
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver
    schema:
      - classpath*:schema-postgresql.sql
  jpa:
    hibernate:
      ddl-auto: update
