spring:
  application:
    name: SMLOCK-${INSTANCE_INDEX:0}
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
